version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - stvnrlnd
  assignees:
  - stvnrlnd
  ignore:
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: facade/ignition
    versions:
    - 1.16.16
    - 1.16.4
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: laravel/helpers
    versions:
    - 1.4.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - stvnrlnd
  assignees:
  - stvnrlnd
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
